/**
 * Auto-generated locale data for languages without dedicated translation files.
 * Each language has core UI strings translated.
 * Languages not listed here will fallback to English.
 */

export const autoLocales: Record<string, Record<string, string>> = {};

// Helper to register a locale quickly
function reg(code: string, s: [string,string,string], t: [string,string,string,string,string,string], h: [string,string,string], st: [string,string,string,string,string,string], sys: [string,string,string]) {
  autoLocales[code] = {
    "sidebar.translate": s[0], "sidebar.history": s[1], "sidebar.settings": s[2],
    "translate.button": t[0], "translate.clear": t[1], "translate.translating": t[2],
    "translate.copy": t[3], "translate.speak": t[4], "translate.original": t[5],
    "history.title": h[0], "history.clearAll": h[1], "history.copied": h[2],
    "settings.title": st[0], "settings.group.translate": st[1], "settings.group.appearance": st[2],
    "settings.group.shortcuts": st[3], "settings.group.chatBubble": st[4], "settings.group.system": st[5],
    "settings.system.language": sys[0], "settings.system.languageDesc": sys[1], "settings.system.version": sys[2],
  };
}

// African languages
reg("af", ["Vertaal","Geskiedenis","Instellings"], ["Vertaal","Vee uit","Vertaal tans...","Kopieer","Lees voor","Oorspronklike"], ["Vertaalgeskiedenis","Vee alles uit","Gekopieer"], ["Instellings","Vertaling","Voorkoms","Kortpaaie","Kletsborreltjie","Stelsel"], ["Koppelvlaktaal","Verander die koppelvlaktaal","Weergawe"]);
reg("am", ["ተርጉም","ታሪክ","ቅንብሮች"], ["ተርጉም","አጽዳ","በመተርጎም ላይ...","ቅዳ","አንብብ","ዋናው"], ["የትርጉም ታሪክ","ሁሉንም አጽዳ","ተቀድቷል"], ["ቅንብሮች","ትርጉም","መልክ","አቋራጮች","የውይይት አረፋ","ስርዓት"], ["የበይነገጽ ቋንቋ","የመተግበሪያ ቋንቋ ቀይር","ስሪት"]);
reg("az", ["Tərcümə","Tarix","Parametrlər"], ["Tərcümə et","Təmizlə","Tərcümə edilir...","Kopyala","Oxu","Orijinal"], ["Tərcümə tarixçəsi","Hamısını sil","Kopyalandı"], ["Parametrlər","Tərcümə","Görünüş","Qısayollar","Söhbət balonu","Sistem"], ["İnterfeys dili","Tətbiq dilini dəyişdir","Versiya"]);
reg("be", ["Пераклад","Гісторыя","Налады"], ["Перакласці","Ачысціць","Пераклад...","Капіяваць","Чытаць","Арыгінал"], ["Гісторыя перакладаў","Ачысціць усё","Скапіявана"], ["Налады","Пераклад","Выгляд","Спалучэнні","Бурбалка","Сістэма"], ["Мова інтэрфейсу","Змяніць мову інтэрфейсу","Версія"]);
reg("bg", ["Превод","История","Настройки"], ["Преведи","Изчисти","Превежда се...","Копирай","Прочети","Оригинал"], ["История на преводите","Изчисти всичко","Копирано"], ["Настройки","Превод","Външен вид","Бързи клавиши","Балонче","Система"], ["Език на интерфейса","Промяна на езика","Версия"]);
reg("bn", ["অনুবাদ","ইতিহাস","সেটিংস"], ["অনুবাদ করুন","মুছুন","অনুবাদ হচ্ছে...","কপি","পড়ুন","মূল"], ["অনুবাদের ইতিহাস","সব মুছুন","কপি হয়েছে"], ["সেটিংস","অনুবাদ","চেহারা","শর্টকাট","চ্যাট বাবল","সিস্টেম"], ["ইন্টারফেস ভাষা","অ্যাপের ভাষা পরিবর্তন করুন","সংস্করণ"]);
reg("bs", ["Prevod","Historija","Postavke"], ["Prevedi","Obriši","Prevodi se...","Kopiraj","Čitaj","Original"], ["Historija prevoda","Obriši sve","Kopirano"], ["Postavke","Prevod","Izgled","Prečice","Oblačić","Sistem"], ["Jezik interfejsa","Promijeni jezik aplikacije","Verzija"]);
reg("ca", ["Tradueix","Historial","Configuració"], ["Tradueix","Esborra","Traduint...","Copia","Llegeix","Original"], ["Historial de traduccions","Esborra tot","Copiat"], ["Configuració","Traducció","Aparença","Dreceres","Bombolla","Sistema"], ["Idioma de la interfície","Canvia l'idioma de l'aplicació","Versió"]);
reg("cs", ["Překlad","Historie","Nastavení"], ["Přeložit","Vymazat","Překládá se...","Kopírovat","Přečíst","Originál"], ["Historie překladů","Vymazat vše","Zkopírováno"], ["Nastavení","Překlad","Vzhled","Zkratky","Bublina","Systém"], ["Jazyk rozhraní","Změnit jazyk aplikace","Verze"]);
reg("cy", ["Cyfieithu","Hanes","Gosodiadau"], ["Cyfieithu","Clirio","Yn cyfieithu...","Copïo","Darllen","Gwreiddiol"], ["Hanes cyfieithu","Clirio popeth","Wedi copïo"], ["Gosodiadau","Cyfieithu","Ymddangosiad","Llwybrau byr","Swigen","System"], ["Iaith rhyngwyneb","Newid iaith yr ap","Fersiwn"]);
reg("da", ["Oversæt","Historik","Indstillinger"], ["Oversæt","Ryd","Oversætter...","Kopiér","Læs op","Original"], ["Oversættelseshistorik","Ryd alt","Kopieret"], ["Indstillinger","Oversættelse","Udseende","Genveje","Chatboble","System"], ["Grænsefladesprog","Skift appens sprog","Version"]);
reg("el", ["Μετάφραση","Ιστορικό","Ρυθμίσεις"], ["Μετάφραση","Εκκαθάριση","Μεταφράζεται...","Αντιγραφή","Ανάγνωση","Πρωτότυπο"], ["Ιστορικό μεταφράσεων","Εκκαθάριση όλων","Αντιγράφηκε"], ["Ρυθμίσεις","Μετάφραση","Εμφάνιση","Συντομεύσεις","Φυσαλίδα","Σύστημα"], ["Γλώσσα διεπαφής","Αλλαγή γλώσσας εφαρμογής","Έκδοση"]);

reg("eo", ["Traduki","Historio","Agordoj"], ["Traduku","Forviŝi","Tradukas...","Kopii","Legi","Originalo"], ["Tradukhistorio","Forviŝi ĉion","Kopiita"], ["Agordoj","Tradukado","Aspekto","Ŝparvojoj","Blobeto","Sistemo"], ["Interfaca lingvo","Ŝanĝi la lingvon","Versio"]);
reg("et", ["Tõlgi","Ajalugu","Seaded"], ["Tõlgi","Kustuta","Tõlgib...","Kopeeri","Loe ette","Originaal"], ["Tõlkeajalugu","Kustuta kõik","Kopeeritud"], ["Seaded","Tõlge","Välimus","Otseteed","Mull","Süsteem"], ["Liidese keel","Muuda rakenduse keelt","Versioon"]);
reg("eu", ["Itzuli","Historia","Ezarpenak"], ["Itzuli","Garbitu","Itzultzen...","Kopiatu","Irakurri","Jatorrizkoa"], ["Itzulpen-historia","Garbitu dena","Kopiatuta"], ["Ezarpenak","Itzulpena","Itxura","Lasterbideak","Burbuila","Sistema"], ["Interfaze-hizkuntza","Aldatu aplikazioaren hizkuntza","Bertsioa"]);
reg("fa", ["ترجمه","تاریخچه","تنظیمات"], ["ترجمه","پاک کردن","در حال ترجمه...","کپی","خواندن","اصلی"], ["تاریخچه ترجمه","پاک کردن همه","کپی شد"], ["تنظیمات","ترجمه","ظاهر","میانبرها","حباب چت","سیستم"], ["زبان رابط","تغییر زبان برنامه","نسخه"]);
reg("fi", ["Käännä","Historia","Asetukset"], ["Käännä","Tyhjennä","Käännetään...","Kopioi","Lue","Alkuperäinen"], ["Käännöshistoria","Tyhjennä kaikki","Kopioitu"], ["Asetukset","Käännös","Ulkoasu","Pikanäppäimet","Kupla","Järjestelmä"], ["Käyttöliittymän kieli","Vaihda sovelluksen kieli","Versio"]);
reg("ga", ["Aistrigh","Stair","Socruithe"], ["Aistrigh","Glan","Ag aistriú...","Cóipeáil","Léigh","Bunaidh"], ["Stair aistriúchán","Glan gach rud","Cóipeáilte"], ["Socruithe","Aistriúchán","Cuma","Aicearraí","Boilgeog","Córas"], ["Teanga comhéadain","Athraigh teanga an aip","Leagan"]);
reg("gl", ["Traducir","Historial","Axustes"], ["Traducir","Borrar","Traducindo...","Copiar","Ler","Orixinal"], ["Historial de traducións","Borrar todo","Copiado"], ["Axustes","Tradución","Aparencia","Atallos","Burbulla","Sistema"], ["Idioma da interface","Cambiar o idioma da aplicación","Versión"]);
reg("gu", ["અનુવાદ","ઇતિહાસ","સેટિંગ્સ"], ["અનુવાદ કરો","સાફ કરો","અનુવાદ થઈ રહ્યો છે...","કૉપિ","વાંચો","મૂળ"], ["અનુવાદ ઇતિહાસ","બધું સાફ કરો","કૉપિ થયું"], ["સેટિંગ્સ","અનુવાદ","દેખાવ","શૉર્ટકટ","ચેટ બબલ","સિસ્ટમ"], ["ઇન્ટરફેસ ભાષા","એપ ભાષા બદલો","સંસ્કરણ"]);
reg("ha", ["Fassara","Tarihi","Saituna"], ["Fassara","Share","Ana fassara...","Kwafi","Karanta","Asali"], ["Tarihin fassara","Share duka","An kwafi"], ["Saituna","Fassara","Bayyanar","Gajerun hanyoyi","Kumfa","Tsarin"], ["Harshen dubawa","Canja harshen app","Sigar"]);
reg("he", ["תרגום","היסטוריה","הגדרות"], ["תרגם","נקה","מתרגם...","העתק","הקרא","מקור"], ["היסטוריית תרגומים","נקה הכל","הועתק"], ["הגדרות","תרגום","מראה","קיצורים","בועת צ'אט","מערכת"], ["שפת ממשק","שנה את שפת האפליקציה","גרסה"]);
reg("hi", ["अनुवाद","इतिहास","सेटिंग्स"], ["अनुवाद करें","साफ़ करें","अनुवाद हो रहा है...","कॉपी","पढ़ें","मूल"], ["अनुवाद इतिहास","सब साफ़ करें","कॉपी हो गया"], ["सेटिंग्स","अनुवाद","दिखावट","शॉर्टकट","चैट बबल","सिस्टम"], ["इंटरफ़ेस भाषा","ऐप की भाषा बदलें","संस्करण"]);
reg("hr", ["Prevedi","Povijest","Postavke"], ["Prevedi","Obriši","Prevodi se...","Kopiraj","Čitaj","Izvornik"], ["Povijest prijevoda","Obriši sve","Kopirano"], ["Postavke","Prijevod","Izgled","Prečaci","Oblačić","Sustav"], ["Jezik sučelja","Promijeni jezik aplikacije","Verzija"]);
reg("ht", ["Tradui","Istwa","Paramèt"], ["Tradui","Efase","Ap tradui...","Kopye","Li","Orijinal"], ["Istwa tradiksyon","Efase tout","Kopye"], ["Paramèt","Tradiksyon","Aparans","Rakousi","Bil","Sistèm"], ["Lang entèfas","Chanje lang aplikasyon an","Vèsyon"]);
reg("hu", ["Fordítás","Előzmények","Beállítások"], ["Fordítás","Törlés","Fordítás...","Másolás","Felolvasás","Eredeti"], ["Fordítási előzmények","Összes törlése","Másolva"], ["Beállítások","Fordítás","Megjelenés","Billentyűk","Buborék","Rendszer"], ["Felület nyelve","Alkalmazás nyelvének módosítása","Verzió"]);
reg("hy", ["Թարգdelays","Պատdelays","Կdelays"], ["Թարգdelays","Մdelays","Թdelays...","Պdelays","Կdelays","Բdelays"], ["Թdelays պdelays","Մdelays բdelays","Պdelays"], ["Կdelays","Թdelays","Տdelays","Դdelays","Պdelays","Հdelays"], ["Ինdelays","Փdelays","Տdelays"]);
reg("id", ["Terjemahkan","Riwayat","Pengaturan"], ["Terjemahkan","Hapus","Menerjemahkan...","Salin","Baca","Asli"], ["Riwayat Terjemahan","Hapus semua","Disalin"], ["Pengaturan","Terjemahan","Tampilan","Pintasan","Gelembung","Sistem"], ["Bahasa antarmuka","Ubah bahasa aplikasi","Versi"]);

reg("ig", ["Sụgharịa","Akụkọ","Ntọala"], ["Sụgharịa","Hichapụ","Na-asụgharị...","Detuo","Gụọ","Izizi"], ["Akụkọ nsụgharị","Hichapụ niile","Edeturu"], ["Ntọala","Nsụgharị","Ọdịdị","Ụzọ mkpirisi","Afụ","Sistemu"], ["Asụsụ","Gbanwee asụsụ ngwa","Ụdị"]);
reg("is", ["Þýða","Saga","Stillingar"], ["Þýða","Hreinsa","Þýðir...","Afrita","Lesa","Upprunalegt"], ["Þýðingasaga","Hreinsa allt","Afritað"], ["Stillingar","Þýðing","Útlit","Flýtileiðir","Blaðra","Kerfi"], ["Viðmótsmál","Breyta tungumáli forrits","Útgáfa"]);
reg("jw", ["Terjemahake","Riwayat","Setelan"], ["Terjemahake","Busak","Nerjemahake...","Salin","Waca","Asli"], ["Riwayat Terjemahan","Busak kabeh","Disalin"], ["Setelan","Terjemahan","Tampilan","Pintasan","Gelembung","Sistem"], ["Basa antarmuka","Ganti basa aplikasi","Versi"]);
reg("ka", ["თარგმნა","ისტორია","პარამეტრები"], ["თარგმნა","გასუფთავება","ითარგმნება...","კოპირება","წაკითხვა","ორიგინალი"], ["თარგმანის ისტორია","ყველას წაშლა","კოპირებულია"], ["პარამეტრები","თარგმანი","გარეგნობა","მალსახმობები","ბუშტი","სისტემა"], ["ინტერფეისის ენა","აპის ენის შეცვლა","ვერსია"]);
reg("kk", ["Аудару","Тарих","Параметрлер"], ["Аудару","Тазалау","Аударылуда...","Көшіру","Оқу","Түпнұсқа"], ["Аударма тарихы","Барлығын тазалау","Көшірілді"], ["Параметрлер","Аударма","Көрініс","Пернелер","Көпіршік","Жүйе"], ["Интерфейс тілі","Қолданба тілін өзгерту","Нұсқа"]);
reg("km", ["បកប្រែ","ប្រវត្តិ","ការកំណត់"], ["បកប្រែ","សម្អាត","កំពុងបកប្រែ...","ចម្លង","អាន","ដើម"], ["ប្រវត្តិបកប្រែ","សម្អាតទាំងអស់","បានចម្លង"], ["ការកំណត់","បកប្រែ","រូបរាង","ផ្លូវកាត់","ពពុះ","ប្រព័ន្ធ"], ["ភាសាចំណុចប្រទាក់","ប្តូរភាសាកម្មវិធី","កំណែ"]);
reg("kn", ["ಅನುವಾದ","ಇತಿಹಾಸ","ಸೆಟ್ಟಿಂಗ್‌ಗಳು"], ["ಅನುವಾದಿಸಿ","ತೆರವುಗೊಳಿಸಿ","ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ...","ನಕಲಿಸಿ","ಓದಿ","ಮೂಲ"], ["ಅನುವಾದ ಇತಿಹಾಸ","ಎಲ್ಲಾ ತೆರವುಗೊಳಿಸಿ","ನಕಲಿಸಲಾಗಿದೆ"], ["ಸೆಟ್ಟಿಂಗ್‌ಗಳು","ಅನುವಾದ","ನೋಟ","ಶಾರ್ಟ್‌ಕಟ್","ಬಬಲ್","ಸಿಸ್ಟಮ್"], ["ಇಂಟರ್ಫೇಸ್ ಭಾಷೆ","ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ ಬದಲಿಸಿ","ಆವೃತ್ತಿ"]);
reg("ku", ["Wergerandin","Dîrok","Mîheng"], ["Wergerîne","Paqij bike","Tê wergerandin...","Kopî bike","Bixwîne","Orîjînal"], ["Dîroka wergerê","Hemû paqij bike","Hat kopîkirin"], ["Mîheng","Werger","Xuyang","Kurterê","Bilbil","Pergal"], ["Zimanê navberê","Zimanê sepanê biguherîne","Guherto"]);
reg("ky", ["Которуу","Тарых","Жөндөөлөр"], ["Которуу","Тазалоо","Которулууда...","Көчүрүү","Окуу","Түпнуска"], ["Которуу тарыхы","Баарын тазалоо","Көчүрүлдү"], ["Жөндөөлөр","Которуу","Көрүнүш","Кыска жолдор","Көбүк","Система"], ["Интерфейс тили","Колдонмо тилин өзгөртүү","Версия"]);
reg("la", ["Verte","Historia","Optiones"], ["Verte","Dele","Vertit...","Copia","Lege","Originale"], ["Historia translationum","Dele omnia","Copiatum"], ["Optiones","Translatio","Aspectus","Compendia","Bulla","Systema"], ["Lingua interfaciei","Muta linguam applicationis","Versio"]);
reg("lb", ["Iwwersetzen","Geschicht","Astellungen"], ["Iwwersetzen","Läschen","Iwwersetzt...","Kopéieren","Liesen","Original"], ["Iwwersetzungsgeschicht","Alles läschen","Kopéiert"], ["Astellungen","Iwwersetzung","Ausgesinn","Ofkierzungen","Blos","System"], ["Sprooch vum Interface","Sprooch vun der App änneren","Versioun"]);
reg("lo", ["ແປ","ປະຫວັດ","ການຕັ້ງຄ່າ"], ["ແປ","ລຶບ","ກຳລັງແປ...","ສຳເນົາ","ອ່ານ","ຕົ້ນສະບັບ"], ["ປະຫວັດການແປ","ລຶບທັງໝົດ","ສຳເນົາແລ້ວ"], ["ການຕັ້ງຄ່າ","ການແປ","ຮູບລັກສະນະ","ທາງລັດ","ຟອງ","ລະບົບ"], ["ພາສາອິນເຕີເຟດ","ປ່ຽນພາສາແອັບ","ເວີຊັນ"]);
reg("lt", ["Versti","Istorija","Nustatymai"], ["Versti","Išvalyti","Verčiama...","Kopijuoti","Skaityti","Originalas"], ["Vertimų istorija","Išvalyti viską","Nukopijuota"], ["Nustatymai","Vertimas","Išvaizda","Spartieji klavišai","Burbulas","Sistema"], ["Sąsajos kalba","Pakeisti programos kalbą","Versija"]);
reg("lv", ["Tulkot","Vēsture","Iestatījumi"], ["Tulkot","Notīrīt","Tulko...","Kopēt","Lasīt","Oriģināls"], ["Tulkojumu vēsture","Notīrīt visu","Nokopēts"], ["Iestatījumi","Tulkojums","Izskats","Saīsnes","Burbulis","Sistēma"], ["Saskarnes valoda","Mainīt lietotnes valodu","Versija"]);
reg("mg", ["Dikao","Tantara","Fikitrohana"], ["Dikao","Fafao","Mandika...","Adikao","Vakio","Tany am-boalohany"], ["Tantaran'ny dikanteny","Fafao daholo","Voatahiry"], ["Fikitrohana","Dikanteny","Endrika","Hafainganam-pitondrana","Vorontsiloza","Rafitra"], ["Fiteny","Ovay ny fitenin'ny rindranasa","Dikan-teny"]);
reg("mi", ["Whakamāori","Hītori","Tautuhinga"], ["Whakamāori","Mukua","E whakamāori ana...","Tārua","Pānui","Taketake"], ["Hītori whakamāoritanga","Mukua katoa","Kua tāruatia"], ["Tautuhinga","Whakamāoritanga","Āhua","Pātene","Mirumiru","Pūnaha"], ["Reo atanga","Hurihia te reo taupānga","Putanga"]);

reg("mk", ["Преведи","Историја","Поставки"], ["Преведи","Избриши","Се преведува...","Копирај","Прочитај","Оригинал"], ["Историја на преводи","Избриши сè","Копирано"], ["Поставки","Превод","Изглед","Кратенки","Балонче","Систем"], ["Јазик на интерфејс","Промени јазик на апликација","Верзија"]);
reg("ml", ["വിവർത്തനം","ചരിത്രം","ക്രമീകരണങ്ങൾ"], ["വിവർത്തനം","മായ്ക്കുക","വിവർത്തനം ചെയ്യുന്നു...","പകർത്തുക","വായിക്കുക","മൂലം"], ["വിവർത്തന ചരിത്രം","എല്ലാം മായ്ക്കുക","പകർത്തി"], ["ക്രമീകരണങ്ങൾ","വിവർത്തനം","രൂപം","കുറുക്കുവഴികൾ","ബബിൾ","സിസ്റ്റം"], ["ഇന്റർഫേസ് ഭാഷ","ആപ്പ് ഭാഷ മാറ്റുക","പതിപ്പ്"]);
reg("mn", ["Орчуулах","Түүх","Тохиргоо"], ["Орчуулах","Цэвэрлэх","Орчуулж байна...","Хуулах","Унших","Эх"], ["Орчуулгын түүх","Бүгдийг цэвэрлэх","Хуулсан"], ["Тохиргоо","Орчуулга","Харагдах байдал","Товчлолууд","Бөмбөлөг","Систем"], ["Интерфэйсийн хэл","Аппын хэлийг солих","Хувилбар"]);
reg("mr", ["भाषांतर","इतिहास","सेटिंग्ज"], ["भाषांतर करा","साफ करा","भाषांतर होत आहे...","कॉपी","वाचा","मूळ"], ["भाषांतर इतिहास","सर्व साफ करा","कॉपी झाले"], ["सेटिंग्ज","भाषांतर","दिसणे","शॉर्टकट","बबल","सिस्टम"], ["इंटरफेस भाषा","अॅप भाषा बदला","आवृत्ती"]);
reg("ms", ["Terjemah","Sejarah","Tetapan"], ["Terjemah","Padam","Menterjemah...","Salin","Baca","Asal"], ["Sejarah Terjemahan","Padam semua","Disalin"], ["Tetapan","Terjemahan","Penampilan","Pintasan","Gelembung","Sistem"], ["Bahasa antara muka","Tukar bahasa aplikasi","Versi"]);
reg("mt", ["Ittraduċi","Storja","Settings"], ["Ittraduċi","Ħassar","Qed jittraduċi...","Ikkopja","Aqra","Oriġinal"], ["Storja tat-traduzzjoni","Ħassar kollox","Ikkupjat"], ["Settings","Traduzzjoni","Dehra","Shortcuts","Bużżieqa","Sistema"], ["Lingwa tal-interface","Ibdel il-lingwa tal-app","Verżjoni"]);
reg("my", ["ဘာသာပြန်","မှတ်တမ်း","ဆက်တင်များ"], ["ဘာသာပြန်","ရှင်းလင်း","ဘာသာပြန်နေသည်...","ကူးယူ","ဖတ်","မူရင်း"], ["ဘာသာပြန်မှတ်တမ်း","အားလုံးရှင်းလင်း","ကူးယူပြီး"], ["ဆက်တင်များ","ဘာသာပြန်","အသွင်အပြင်","ဖြတ်လမ်း","ပူဖောင်း","စနစ်"], ["မျက်နှာပြင်ဘာသာ","အက်ပ်ဘာသာစကားပြောင်း","ဗားရှင်း"]);
reg("ne", ["अनुवाद","इतिहास","सेटिङ्स"], ["अनुवाद गर्नुहोस्","खाली गर्नुहोस्","अनुवाद हुँदैछ...","कपी","पढ्नुहोस्","मूल"], ["अनुवाद इतिहास","सबै खाली गर्नुहोस्","कपी भयो"], ["सेटिङ्स","अनुवाद","देखावट","सर्टकट","बबल","प्रणाली"], ["इन्टरफेस भाषा","एप भाषा परिवर्तन गर्नुहोस्","संस्करण"]);
reg("nl", ["Vertalen","Geschiedenis","Instellingen"], ["Vertaal","Wissen","Vertalen...","Kopiëren","Voorlezen","Origineel"], ["Vertaalgeschiedenis","Alles wissen","Gekopieerd"], ["Instellingen","Vertaling","Uiterlijk","Sneltoetsen","Bubbel","Systeem"], ["Interfacetaal","Wijzig de app-taal","Versie"]);
reg("no", ["Oversett","Historikk","Innstillinger"], ["Oversett","Tøm","Oversetter...","Kopier","Les opp","Original"], ["Oversettelseshistorikk","Tøm alt","Kopiert"], ["Innstillinger","Oversettelse","Utseende","Snarveier","Boble","System"], ["Grensesnittspråk","Endre appens språk","Versjon"]);
reg("ny", ["Masulira","Mbiri","Zosintha"], ["Masulira","Chotsani","Kumasulira...","Koperani","Werengani","Choyambirira"], ["Mbiri yomasulira","Chotsani zonse","Zakopera"], ["Zosintha","Kumasulira","Maonekedwe","Njira zaufupi","Thumba","Dongosolo"], ["Chilankhulo","Sinthani chilankhulo cha app","Mtundu"]);
reg("pa", ["ਅਨੁਵਾਦ","ਇਤਿਹਾਸ","ਸੈਟਿੰਗਾਂ"], ["ਅਨੁਵਾਦ ਕਰੋ","ਸਾਫ਼ ਕਰੋ","ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ...","ਕਾਪੀ","ਪੜ੍ਹੋ","ਮੂਲ"], ["ਅਨੁਵਾਦ ਇਤਿਹਾਸ","ਸਭ ਸਾਫ਼ ਕਰੋ","ਕਾਪੀ ਹੋ ਗਿਆ"], ["ਸੈਟਿੰਗਾਂ","ਅਨੁਵਾਦ","ਦਿੱਖ","ਸ਼ਾਰਟਕੱਟ","ਬਬਲ","ਸਿਸਟਮ"], ["ਇੰਟਰਫੇਸ ਭਾਸ਼ਾ","ਐਪ ਭਾਸ਼ਾ ਬਦਲੋ","ਸੰਸਕਰਣ"]);
reg("pl", ["Tłumacz","Historia","Ustawienia"], ["Tłumacz","Wyczyść","Tłumaczenie...","Kopiuj","Czytaj","Oryginał"], ["Historia tłumaczeń","Wyczyść wszystko","Skopiowano"], ["Ustawienia","Tłumaczenie","Wygląd","Skróty","Dymek","System"], ["Język interfejsu","Zmień język aplikacji","Wersja"]);
reg("ps", ["ژباړه","تاریخ","تنظیمات"], ["ژباړه","پاکول","ژباړل کیږي...","کاپي","لوستل","اصلي"], ["د ژباړې تاریخ","ټول پاکول","کاپي شو"], ["تنظیمات","ژباړه","بڼه","لنډلارې","حباب","سیسټم"], ["د انٹرفیس ژبه","د اپلیکیشن ژبه بدلول","نسخه"]);
reg("ro", ["Traducere","Istoric","Setări"], ["Traduce","Șterge","Se traduce...","Copiază","Citește","Original"], ["Istoric traduceri","Șterge tot","Copiat"], ["Setări","Traducere","Aspect","Comenzi rapide","Balon","Sistem"], ["Limba interfeței","Schimbă limba aplicației","Versiune"]);
reg("rw", ["Guhindura","Amateka","Igenamiterere"], ["Hindura","Siba","Birahindurwa...","Gukoporora","Soma","Umwimerere"], ["Amateka y'ubuhinduzi","Siba byose","Byakopowe"], ["Igenamiterere","Ubuhinduzi","Isura","Inzira ngufi","Akabuto","Sisitemu"], ["Ururimi rw'ikoranabuhanga","Hindura ururimi rw'porogaramu","Verisiyo"]);

reg("sd", ["ترجمو","تاريخ","سيٽنگون"], ["ترجمو ڪريو","صاف ڪريو","ترجمو ٿي رهيو آهي...","نقل","پڙهو","اصل"], ["ترجمي جي تاريخ","سڀ صاف ڪريو","نقل ٿيو"], ["سيٽنگون","ترجمو","ظاهر","شارٽ ڪٽ","بلبلو","سسٽم"], ["انٽرفيس ٻولي","ايپ جي ٻولي تبديل ڪريو","ورزن"]);
reg("si", ["පරිවර්තනය","ඉතිහාසය","සැකසුම්"], ["පරිවර්තනය","මකන්න","පරිවර්තනය වෙමින්...","පිටපත්","කියවන්න","මුල්"], ["පරිවර්තන ඉතිහාසය","සියල්ල මකන්න","පිටපත් විය"], ["සැකසුම්","පරිවර්තනය","පෙනුම","කෙටිමං","බුබුළ","පද්ධතිය"], ["අතුරුමුහුණත් භාෂාව","යෙදුම් භාෂාව වෙනස් කරන්න","අනුවාදය"]);
reg("sk", ["Preložiť","História","Nastavenia"], ["Preložiť","Vymazať","Prekladá sa...","Kopírovať","Prečítať","Originál"], ["História prekladov","Vymazať všetko","Skopírované"], ["Nastavenia","Preklad","Vzhľad","Skratky","Bublina","Systém"], ["Jazyk rozhrania","Zmeniť jazyk aplikácie","Verzia"]);
reg("sl", ["Prevedi","Zgodovina","Nastavitve"], ["Prevedi","Počisti","Prevajanje...","Kopiraj","Preberi","Izvirnik"], ["Zgodovina prevodov","Počisti vse","Kopirano"], ["Nastavitve","Prevod","Videz","Bližnjice","Mehurček","Sistem"], ["Jezik vmesnika","Spremeni jezik aplikacije","Različica"]);
reg("sm", ["Faaliliu","Tala faasolopito","Faatulagaga"], ["Faaliliu","Tape","O faaliliu...","Kopi","Faitau","Uluai"], ["Tala faasolopito o faaliliuga","Tape uma","Ua kopi"], ["Faatulagaga","Faaliliuga","Foliga","Auala puupuu","Pulu","Faiga"], ["Gagana o le ata","Sui le gagana o le app","Lomiga"]);
reg("sn", ["Shandura","Nhoroondo","Zvigadziriso"], ["Shandura","Dzima","Kushandura...","Kopera","Verenga","Chekutanga"], ["Nhoroondo yekushandura","Dzima zvese","Yakopera"], ["Zvigadziriso","Kushandura","Chimiro","Nzira pfupi","Bhabhuru","System"], ["Mutauro wechiso","Chinja mutauro weapp","Shanduro"]);
reg("so", ["Turjun","Taariikhda","Dejinta"], ["Turjun","Tirtir","Waa la turjumayaa...","Koobiyee","Akhri","Asalka"], ["Taariikhda turjumaadda","Tirtir dhammaan","Waa la koobiyeeyay"], ["Dejinta","Turjumaad","Muuqaalka","Fure gaaban","Xumbo","Nidaamka"], ["Luqadda","Beddel luqadda app-ka","Nooca"]);
reg("sq", ["Përkthe","Historia","Cilësimet"], ["Përkthe","Pastro","Po përkthen...","Kopjo","Lexo","Origjinali"], ["Historia e përkthimeve","Pastro të gjitha","U kopjua"], ["Cilësimet","Përkthimi","Pamja","Shkurtoret","Flluskë","Sistemi"], ["Gjuha e ndërfaqes","Ndrysho gjuhën e aplikacionit","Versioni"]);
reg("sr", ["Преведи","Историја","Подешавања"], ["Преведи","Обриши","Преводи се...","Копирај","Прочитај","Оригинал"], ["Историја превода","Обриши све","Копирано"], ["Подешавања","Превод","Изглед","Пречице","Облачић","Систем"], ["Језик интерфејса","Промени језик апликације","Верзија"]);
reg("st", ["Fetolela","Nalane","Litlhophiso"], ["Fetolela","Hlakola","E fetoleloa...","Kopitsa","Bala","Ea pele"], ["Nalane ea liphetolelo","Hlakola tsohle","E kopitsoe"], ["Litlhophiso","Phetolelo","Ponahalo","Litsela tse khutšoane","Leqhubu","Tsamaiso"], ["Puo ea sebopeho","Fetola puo ea app","Mofuta"]);
reg("su", ["Tarjamahkeun","Sajarah","Setélan"], ["Tarjamahkeun","Hapus","Narjamahkeun...","Tiron","Baca","Asli"], ["Sajarah Tarjamahan","Hapus sadaya","Disalin"], ["Setélan","Tarjamahan","Tampilan","Potong kompas","Gelembung","Sistem"], ["Basa antarmuka","Robih basa aplikasi","Vérsi"]);
reg("sv", ["Översätt","Historik","Inställningar"], ["Översätt","Rensa","Översätter...","Kopiera","Läs upp","Original"], ["Översättningshistorik","Rensa allt","Kopierat"], ["Inställningar","Översättning","Utseende","Genvägar","Bubbla","System"], ["Gränssnittsspråk","Ändra appens språk","Version"]);
reg("sw", ["Tafsiri","Historia","Mipangilio"], ["Tafsiri","Futa","Inatafsiri...","Nakili","Soma","Asili"], ["Historia ya tafsiri","Futa yote","Imenakiliwa"], ["Mipangilio","Tafsiri","Muonekano","Njia za mkato","Kiputo","Mfumo"], ["Lugha ya kiolesura","Badilisha lugha ya programu","Toleo"]);
reg("ta", ["மொழிபெயர்","வரலாறு","அமைப்புகள்"], ["மொழிபெயர்","அழி","மொழிபெயர்க்கிறது...","நகலெடு","படி","மூலம்"], ["மொழிபெயர்ப்பு வரலாறு","அனைத்தையும் அழி","நகலெடுக்கப்பட்டது"], ["அமைப்புகள்","மொழிபெயர்ப்பு","தோற்றம்","குறுக்குவழிகள்","குமிழி","அமைப்பு"], ["இடைமுக மொழி","பயன்பாட்டு மொழியை மாற்று","பதிப்பு"]);
reg("te", ["అనువాదం","చరిత్ర","సెట్టింగ్‌లు"], ["అనువదించు","క్లియర్","అనువదిస్తోంది...","కాపీ","చదువు","అసలు"], ["అనువాద చరిత్ర","అన్నీ క్లియర్","కాపీ అయింది"], ["సెట్టింగ్‌లు","అనువాదం","రూపం","షార్ట్‌కట్‌లు","బబుల్","సిస్టమ్"], ["ఇంటర్‌ఫేస్ భాష","యాప్ భాష మార్చు","వెర్షన్"]);
reg("tg", ["Тарҷума","Таърих","Танзимот"], ["Тарҷума кунед","Тоза кунед","Тарҷума мешавад...","Нусхабардорӣ","Хонед","Аслӣ"], ["Таърихи тарҷума","Ҳамаро тоза кунед","Нусхабардорӣ шуд"], ["Танзимот","Тарҷума","Намуд","Миёнбурҳо","Ҳубоб","Система"], ["Забони интерфейс","Забони барномаро иваз кунед","Версия"]);
reg("th", ["แปล","ประวัติ","ตั้งค่า"], ["แปล","ล้าง","กำลังแปล...","คัดลอก","อ่าน","ต้นฉบับ"], ["ประวัติการแปล","ล้างทั้งหมด","คัดลอกแล้ว"], ["ตั้งค่า","การแปล","ลักษณะ","ทางลัด","ฟองแชท","ระบบ"], ["ภาษาอินเทอร์เฟซ","เปลี่ยนภาษาแอป","เวอร์ชัน"]);
reg("tl", ["Isalin","Kasaysayan","Mga Setting"], ["Isalin","I-clear","Nagsasalin...","Kopyahin","Basahin","Orihinal"], ["Kasaysayan ng Pagsasalin","I-clear lahat","Nakopya"], ["Mga Setting","Pagsasalin","Hitsura","Mga Shortcut","Bubble","Sistema"], ["Wika ng interface","Baguhin ang wika ng app","Bersyon"]);
reg("tt", ["Тәрҗемә","Тарих","Көйләүләр"], ["Тәрҗемә ит","Чистарт","Тәрҗемә ителә...","Күчереп ал","Укы","Оригинал"], ["Тәрҗемә тарихы","Барысын бетерү","Күчерелде"], ["Көйләүләр","Тәрҗемә","Күренеш","Кыскартмалар","Шар","Система"], ["Интерфейс теле","Кушымта телен үзгәртү","Версия"]);
reg("ug", ["تەرجىمە","تارىخ","تەڭشەكلەر"], ["تەرجىمە","تازىلاش","تەرجىمە قىلىنىۋاتىدۇ...","كۆچۈرۈش","ئوقۇش","ئەسلى"], ["تەرجىمە تارىخى","ھەممىنى تازىلاش","كۆچۈرۈلدى"], ["تەڭشەكلەر","تەرجىمە","كۆرۈنۈش","تېزلەتمە","كۆپۈكچە","سىستېما"], ["كۆرۈنمە تىلى","ئەپ تىلىنى ئۆزگەرتىش","نەشرى"]);
reg("uk", ["Перекласти","Історія","Налаштування"], ["Перекласти","Очистити","Перекладає...","Копіювати","Прочитати","Оригінал"], ["Історія перекладів","Очистити все","Скопійовано"], ["Налаштування","Переклад","Вигляд","Гарячі клавіші","Бульбашка","Система"], ["Мова інтерфейсу","Змінити мову додатку","Версія"]);
reg("ur", ["ترجمہ","تاریخ","ترتیبات"], ["ترجمہ کریں","صاف کریں","ترجمہ ہو رہا ہے...","کاپی","پڑھیں","اصل"], ["ترجمے کی تاریخ","سب صاف کریں","کاپی ہو گیا"], ["ترتیبات","ترجمہ","ظاہری شکل","شارٹ کٹ","بلبلہ","سسٹم"], ["انٹرفیس زبان","ایپ کی زبان تبدیل کریں","ورژن"]);
reg("uz", ["Tarjima","Tarix","Sozlamalar"], ["Tarjima qilish","Tozalash","Tarjima qilinmoqda...","Nusxalash","O'qish","Asl"], ["Tarjima tarixi","Hammasini tozalash","Nusxalandi"], ["Sozlamalar","Tarjima","Ko'rinish","Yorliqlar","Pufakcha","Tizim"], ["Interfeys tili","Ilova tilini o'zgartirish","Versiya"]);
reg("vi", ["Dịch","Lịch sử","Cài đặt"], ["Dịch","Xóa","Đang dịch...","Sao chép","Đọc","Gốc"], ["Lịch sử dịch","Xóa tất cả","Đã sao chép"], ["Cài đặt","Dịch thuật","Giao diện","Phím tắt","Bong bóng","Hệ thống"], ["Ngôn ngữ giao diện","Đổi ngôn ngữ ứng dụng","Phiên bản"]);
reg("xh", ["Guqulela","Imbali","Izicwangciso"], ["Guqulela","Sula","Iyaguqulela...","Khuphela","Funda","Eyokuqala"], ["Imbali yokuguqulela","Sula konke","Ikhutshelwe"], ["Izicwangciso","Ukuguqulela","Imbonakalo","Izinqamla","Ibhabha","Inkqubo"], ["Ulwimi lwe-interface","Tshintsha ulwimi lwe-app","Uhlelo"]);
reg("yi", ["איבערזעצן","געשיכטע","אויסשטעלונגען"], ["איבערזעצן","אויסמעקן","איבערזעצט...","קאפירן","לייענען","אריגינאל"], ["איבערזעצונג געשיכטע","אויסמעקן אלץ","קאפירט"], ["אויסשטעלונגען","איבערזעצונג","אויסזען","קורצוועגן","בלאָז","סיסטעם"], ["אינטערפייס שפּראַך","ביטן אַפּ שפּראַך","ווערסיע"]);
reg("yo", ["Túmọ̀","Ìtàn","Ètò"], ["Túmọ̀","Pa rẹ́","Ń túmọ̀...","Dà kọ","Ka","Àkọ́kọ́"], ["Ìtàn ìtúmọ̀","Pa gbogbo rẹ̀","Ti dà kọ"], ["Ètò","Ìtúmọ̀","Ìrísí","Ọ̀nà àbájáde","Fèéfé","Ètò ẹ̀rọ"], ["Èdè atọ́kùn","Yí èdè àpù padà","Ẹ̀yà"]);
reg("zu", ["Humusha","Umlando","Izilungiselelo"], ["Humusha","Sula","Kuhunyushwa...","Kopisha","Funda","Okwangempela"], ["Umlando wokuhumusha","Sula konke","Kukopishiwe"], ["Izilungiselelo","Ukuhumusha","Ukubukeka","Izinqamuleli","Ibhabula","Isistimu"], ["Ulimi lwe-interface","Shintsha ulimi lwe-app","Inguqulo"]);
reg("hy", ["Թargmanel","Պatmutyun","Kargatsakner"], ["Targmanel","Maqrel","Targmanvum e...","Patčenel","Kardal","Bnagir"], ["Targmanowtyunneri patmutyun","Maqrel bolore","Patčenvats e"], ["Kargatsakner","Targmanutyun","Artaqin tesk","Dryunčner","Prpruk","Hamakarq"], ["Interfeysi lezu","P'oxel havelvaci lezu","Tarberак"]);

